jogovarejo/urls.py
from django.urls import path, re_path

from . import views

app_name = "jogovarejo"
urlpatterns = [
    path ('',                           views.index,             name='index'),     
    path ('formula/<int:numeroGrupo>/', views.detalheFormulacao, name="detalheFormulacao"), 
    path ('salvametodo/',               views.salvaMetodo,       name='salvaMetodo'),
    path ('simula/<int:numeroGrupo>/',  views.detalheSimulacao,  name="detalheSimulacao"), 
    path ('avancadia/',                 views.avancaUmDia,       name='avancaUmDia'),
    path ('retrocede1dia/',             views.retrocedeUmdia,    name='retrocedeUmdia'),
    path ('avalia/<int:numeroGrupo>/',  views.detalheAvaliacao,  name="detalheAvaliacao"), 
    path ('decisoes/',                  views.decisoesDosGrupos, name='decisoesDosGrupos'), 
    path ('avanca/',                    views.avancaFase,        name='avancaFase'), 
    path ('retrocede/',                 views.retrocedeFase,     name='retrocedeFase'), 
    path ('sobre/',                     views.sobre,             name='sobre'),
    re_path(r'^.*\.*', views.pages, name='pages'),  # Essa linha precisa ser a última porque é ela que trata as URLs inexistentes (todas não tratadas até ela)   
] 

jogovarejoweb/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from jogovarejo import views

# Modo mais simples sugerido para acesso a API:
router = routers.DefaultRouter()
router.register (r'indicadores', views.IndicadoresViewSet)
router.register (r'grupos', views.GruposViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')), # Auth routes - login / register
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')), # caminho p/login na API
    path('', include('jogovarejo.urls')), # Essa linha precisa ser a última porque ela contém a "re_path (...., views.pages, ....)" (que trata as URLs inexistentes)       
]

jogovarejo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from django import template
from django.template import loader
from rest_framework import viewsets, permissions

from .models import Controle, Grupo, Movimento, IndicadoresDoGrupo
from .dinamica import ProcessaUmDia, RetrocedeUmDia
from .serializers import IndicadoresSerializer, GruposSerializer


def numeroGrupoDoUsuario (loginUsuario):
    if loginUsuario   == 'grupo1':  numGrupo = 1
    elif loginUsuario == 'grupo2':  numGrupo = 2
    elif loginUsuario == 'grupo3':  numGrupo = 3
    elif loginUsuario == 'grupo4':  numGrupo = 4
    elif loginUsuario == 'grupo5':  numGrupo = 5
    elif loginUsuario == 'grupo6':  numGrupo = 6
    elif loginUsuario == 'grupo7':  numGrupo = 7
    elif loginUsuario == 'grupo8':  numGrupo = 8
    elif loginUsuario == 'grupo9':  numGrupo = 9
    elif loginUsuario == 'grupo10': numGrupo = 10
    elif loginUsuario == 'grupo11': numGrupo = 11
    elif loginUsuario == 'grupo12': numGrupo = 12
    return numGrupo


@login_required(login_url="/login/")
def index (request):
    loginUsuario = request.user.username
    if loginUsuario == 'professor':
        controle = Controle.objects.filter (Nome='Ativo').first()
        grupos = Grupo.objects.filter (Ativo=True).order_by ('Numero')
        contexto = {'tela'   : 'professor', 
                    'fase'   : controle.Fase,
                    'grupos' : grupos}
        return render (request, 'jogovarejo/index.html', contexto)
    else:
        numGrupo = numeroGrupoDoUsuario (loginUsuario)
        fase = Controle.objects.filter (Nome='Ativo').first().Fase
        if fase == 1:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheFormulacao', args=(str(numGrupo))))
        elif fase == 2:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(str(numGrupo))))
        elif fase == 3:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheAvaliacao', args=(str(numGrupo))))


@login_required(login_url="/login/")
def salvaMetodo (request):
    if request.method == 'POST':
        numGrupo = request.POST.get('numGrupo')
        quando   = request.POST.get('quando')
        quanto   = request.POST.get('quanto')
        try:
            grupo = Grupo.objects.get(Numero=numGrupo)
            grupo.Quando  = quando
            grupo.Quanto  = quanto
            grupo.Fase1Ok = True
            grupo.save()
            messages.success (request, 'Gravação bem sucedida! Aguarde a Fase 2 ou altere seu método, se desejar.')
        except ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheFormulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def detalheFormulacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = Grupo.objects.get(Numero=numeroGrupo)
    contexto = {'tela'       : 'alunoFormulacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo}
    return render (request, 'jogovarejo/detalheformula.html', contexto)


@login_required(login_url="/login/")
def avancaUmDia (request):
    if request.method == 'POST':
        numGrupo        = request.POST.get('numGrupo')
        diaNaEstacaoStr = request.POST.get('diaCorrenteNaEstacao')
        quantidadeStr   = request.POST.get('novaCompra')
        try:
            grOperador = Grupo.objects.get (Numero=numGrupo)
            grGerente  = Grupo.objects.filter (GrupoOperador=grOperador).first()
            diaNaEstacao = int (diaNaEstacaoStr)
            if diaNaEstacao == grGerente.DiaCorrente:
                try:
                    quantidade = int (quantidadeStr)
                    if quantidade >= 0:
                        mensagem = ProcessaUmDia (grGerente, quantidade)
                        messages.success (request, mensagem)
                    else:
                        messages.error (request, 'Edição inválida. Tente de novo')
                except ValueError:
                    messages.error (request, 'Edição inválida. Tente de novo')
            else:
                messages.error (request, 'Data inválida.')
        except ValueError or ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def retrocedeUmdia (request):
    if request.method == 'POST':
        numGrupo = request.POST.get('numGrupo')
        try:
            grOperador = Grupo.objects.get (Numero=numGrupo)
            grGerente  = Grupo.objects.filter (GrupoOperador=grOperador).first()
            mensagem = RetrocedeUmDia (grGerente)
            messages.success (request, mensagem)
        except ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def detalheSimulacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = Grupo.objects.get(Numero=numeroGrupo)  # "grupo" é o grupo operador
    grGerente  = Grupo.objects.filter (GrupoOperador=grupo).first()
    moviDeHoje = Movimento.objects.filter(Grupo=grGerente, Dia=grGerente.DiaCorrente).first()
    historico  = Movimento.objects.filter (Grupo=grGerente).order_by ('Dia')
    contexto = {'tela'       : 'alunoSimulacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo,    # "grupo" é o grupo operador
                'hoje'       : grupo.DiaCorrenteDoGrupoComoOperador, 
                'grGerente'  : grGerente,
                'moviDeHoje' : moviDeHoje,
                'historico'  : historico}
    return render (request, 'jogovarejo/detalhesimula.html', contexto)


@login_required(login_url="/login/")
def detalheAvaliacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = IndicadoresDoGrupo.objects.get(Numero=numeroGrupo)
    historico  = Movimento.objects.filter (Grupo=grupo).order_by ('Dia')
    contexto = {'tela'       : 'alunoAvaliacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo,
                'hoje'       : grupo.DiaCorrente, 
                'historico'  : historico}
    return render (request, 'jogovarejo/detalheavalia.html', contexto)


def obtemDecisoesDosGrupos ():
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupos = Grupo.objects.filter (Ativo=True).order_by ('Numero')
    # Cria primeira linha (que será mostrada como primeira coluna) para mostrar os dias:
    decisoes = []
    decisoesGrupo = ['Dia']
    for dia in range (1, controle.Duracao+1):
        decisoesGrupo.append (dia)
    decisoes.append (decisoesGrupo)
    # Inicializa restante da matriz com nome dos grupos e decisão "-1":
    for grupo in grupos:
        decisoesGrupo = [grupo.Numero]
        for dia in range (1, controle.Duracao+1):
            decisoesGrupo.append (-1)
        decisoes.append (decisoesGrupo)
    # Agora obtem e atribui decisoes:
    for grupo in grupos:
        historico  = Movimento.objects.filter (Grupo=grupo).order_by ('Dia')
        for histDia in historico:
            if histDia.Comprado != None:
                decisoes [grupo.Numero] [histDia.Dia] = histDia.Comprado
    # Por fim transpõe a matriz, pois será construida linha a linha (grupos nas colunas, dias nas linhas)
        decisoes_transpostas = list (map (list, zip(*decisoes)))
        # Para entender o comando acima:
        # - o operador "*" desempacota a "lista de lista" em "listas"
        # - a função "zip" transpõe os elementos das listas recebidas retornando-as como tuplas
        # - a função "list" mais interna transforma uma tupla em uma lista
        # - a função "map" aplica a função "list" a cada uma das tuplas transformando-as, portanto, em listas
        # - a função "list" mais externa, por fim, transforma o conjunto de listas em uma lista de listas
    return decisoes_transpostas


@login_required(login_url="/login/")
def decisoesDosGrupos (request):
    controle = Controle.objects.filter (Nome='Ativo').first()
    contexto = {'tela'     : 'decisoes',
                'fase'     : controle.Fase,
                'decisoes' : obtemDecisoesDosGrupos}
    return render (request, 'jogovarejo/decisoes.html', contexto)


@login_required(login_url="/login/")
def avancaFase (request):
    if request.method == 'POST':
        controle = Controle.objects.filter (Nome='Ativo').first()
        if controle.Fase < 3:
            controle.Fase += 1
            controle.save()
            messages.success (request, 'Fase avançada com sucesso')
        else:
            messages.error (request, 'Não foi possivel avançar de fase')
    return HttpResponseRedirect (reverse ('jogovarejo:index'))


@login_required(login_url="/login/")
def retrocedeFase (request):
    if request.method == 'POST':
        controle = Controle.objects.filter (Nome='Ativo').first()
        if controle.Fase > 1:
            controle.Fase -= 1
            controle.save()
            messages.success (request, 'Fase retrocedida com sucesso')
        else:
            messages.error (request, 'Não foi possivel retroceder fase')
    return HttpResponseRedirect (reverse ('jogovarejo:index'))


@login_required(login_url="/login/")
def sobre (request):
    contexto = {'tela' : 'sobre'}
    return render (request, 'jogovarejo/sobre.html', contexto)

jogovarejo/templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
    <div class="row">
        <div class="col-12 col-md-8 col-xl-8 mb-4 mb-md-0">
            <p class="mb-0 text-start">
                &copy; SOMA Tecnologia e Sistemas para Operações e Manufatura Ltda.
            </p>
        </div>
        <div class="col-12 col-md-4 col-xl-4">
            <ul class="list-inline list-group-flush list-group-borderless text-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    Versão 2024
                </li>
            </ul>
        </div>
    </div>
</footer>

jogovarejo/templates/includes/sidebar.html
{% load static %}

<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">     <!-- PARECE NECESSÁRIO PARA CELULAR. REVER ISSO" -->
    <a class="navbar-brand me-lg-5" href="/">
        <img class="navbar-brand-dark" src="{% static 'assets/img/brand/light.svg' %}" alt="Volt logo" /> <img class="navbar-brand-light" src="{% static 'assets/img/brand/dark.svg' %}" alt="Volt logo" />
        <b> Jogo Varejo </b>
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">

        <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">     <!-- PARECE NECESSÁRIO PARA CELULAR. REVER ISSO" -->
            <div class="d-flex align-items-center">
                <div class="d-block">
                    <h2 class="h5 mb-3">Olá, {{ request.user.username }}</h2>
                    <form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                            <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
                            Logout
                        </button>
                    </form>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
            </div>
        </div>

        <ul class="nav flex-column pt-3 pt-md-0">
            <li class="nav-item">     <!-- Título "JOGO VAREJO" -->
                <a href="{% url 'jogovarejo:index' %}" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <img src="{% static 'assets/img/brand/light.svg' %}" height="20" width="20" alt="Volt Logo">
                    </span>
                    <span class="mt-1 ms-1 sidebar-text">Jogo Varejo</span>
                </a>
            </li>

            {% if request.user.username == 'professor' %}
                <li class="nav-item {% if tela == 'professor' %} active {% endif %}">   <!-- Botao "JOGAR" -->
                    <a href="{% url 'jogovarejo:index' %}" class="nav-link">
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814z"/>
                                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm15 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1z"/>
                            </svg>
                        </span>
                        <span class="sidebar-text">Jogar</span>
                    </a>
                </li>
            {% endif %}

            {% if request.user.username == 'professor' %}
                <li class="nav-item {% if tela == 'decisoes' %} active {% endif %}">   <!-- Botao "JOGAR" -->
                    <a href="{% url 'jogovarejo:decisoesDosGrupos' %}" class="nav-link">
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                                <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
                            </svg>
                        </span>
                        <span class="sidebar-text">Decisões de compra</span>
                    </a>
                </li>
            {% endif %}

            {% if grupo %}
                <li class="nav-item {% if tela == 'alunoFormulacao' %} active {% endif %}">   <!-- Botao "DETALHE FORMULACAO" -->
                    <a href="{% url 'jogovarejo:detalheFormulacao' grupo.Numero %}" class="nav-link">
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
                                <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
                            </svg>
                        </span>
                        <span class="sidebar-text">Formulação (Fase 1)</span>
                        </label>
                    </a>
                </li>
            {% endif %}

            {% if grupo %}
            {% if fase >= 2 or request.user.username == 'professor'%}
                <li class="nav-item {% if tela == 'alunoSimulacao' %} active {% endif %}">   <!-- Botao "DETALHE SIMULACAO" -->
                    <a href="{% url 'jogovarejo:detalheSimulacao' grupo.Numero %}" class="nav-link">
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 12V4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2m6.79-6.907A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814z"/>
                            </svg>
                        </span>
                        <span class="sidebar-text">Simulação (Fase 2)</span>
                        </label>
                    </a>
                </li>
            {% endif %}
            {% endif %}

            {% if grupo %}
            {% if fase == 3 or request.user.username == 'professor' or grupo.Fase2DoGrupoComoOperadorOk == True %}
                <li class="nav-item {% if tela == 'alunoAvaliacao' %} active {% endif %}">   <!-- Botao "DETALHE AVALIACAO" -->
                    <a href="{% url 'jogovarejo:detalheAvaliacao' grupo.Numero %}" class="nav-link">
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                                <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
                            </svg>                        
                        </span>
                        <span class="sidebar-text">Avaliação (Fase 3)</span>
                        </label>
                    </a>
                </li>
            {% endif %}
            {% endif %}

            {% if request.user.username == 'professor' %}
                <li class="nav-item">     <!-- Botao "AVANCAR FASE" -->
                    <div class="nav-link d-flex align-items-center">
                        <form id="avancaFase" method="post" action="{% url 'jogovarejo:avancaFase'%}">
                            {% csrf_token %}
                            <span class="sidebar-icon">
                                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
                                </svg>
                            </span>
                            <span class="sidebar-text" onclick="document.getElementById('avancaFase').submit()">Avançar fase</span>
                        </form>
                    </div>
                </li>
            {% endif %}

            {% if request.user.username == 'professor' %}
                <li class="nav-item">     <!-- Botao "RETROCEDER FASE" -->
                    <div class="nav-link d-flex align-items-center">
                        <form id="voltaFase" method="post" action="{% url 'jogovarejo:retrocedeFase'%}">
                            {% csrf_token %}
                            <span class="sidebar-icon">
                                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z" />
                                </svg>
                            </span>
                            <span class="sidebar-text" onclick="document.getElementById('voltaFase').submit()">Retroceder fase</span>
                        </form>
                    </div>
                </li>
            {% endif %}

            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>

            <li class="nav-item {% if tela == 'sobre' %} active {% endif %}">     <!-- Botao "SOBRE" -->
                <a href="{% url 'jogovarejo:sobre' %}" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                        </svg>
                    </span>
                    <span class="sidebar-text">Sobre</span>
                </a>
            </li>

            {% if grupo %}
            {% if tela == 'alunoSimulacao' or tela == 'alunoAvaliacao' %}
                <li class="nav-item">     <!-- Indicação do DIA CORRENTE -->
                    <div class="btn btn-lg btn-secondary d-flex align-items-center justify-content-center btn-upgrade-pro">
                        <span>
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">

                                <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>

                            </svg>
                        </span>
                        <span>Dia {{ hoje }}</span>
                    </div>
                </li>
            {% endif %}
            {% endif %}
        </ul>

    </div>
</nav>