jogovarejo/urls.py
from django.urls import path, re_path

from . import views

app_name = "jogovarejo"
urlpatterns = [
    path ('',                           views.index,             name='index'),     
    path ('formula/<int:numeroGrupo>/', views.detalheFormulacao, name="detalheFormulacao"), 
    path ('salvametodo/',               views.salvaMetodo,       name='salvaMetodo'),
    path ('simula/<int:numeroGrupo>/',  views.detalheSimulacao,  name="detalheSimulacao"), 
    path ('avancadia/',                 views.avancaUmDia,       name='avancaUmDia'),
    path ('retrocede1dia/',             views.retrocedeUmdia,    name='retrocedeUmdia'),
    path ('avalia/<int:numeroGrupo>/',  views.detalheAvaliacao,  name="detalheAvaliacao"), 
    path ('decisoes/',                  views.decisoesDosGrupos, name='decisoesDosGrupos'), 
    path ('avanca/',                    views.avancaFase,        name='avancaFase'), 
    path ('retrocede/',                 views.retrocedeFase,     name='retrocedeFase'), 
    path ('sobre/',                     views.sobre,             name='sobre'),
    re_path(r'^.*\.*', views.pages, name='pages'),  # Essa linha precisa ser a última porque é ela que trata as URLs inexistentes (todas não tratadas até ela)   
] 

jogovarejoweb/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from jogovarejo import views

# Modo mais simples sugerido para acesso a API:
router = routers.DefaultRouter()
router.register (r'indicadores', views.IndicadoresViewSet)
router.register (r'grupos', views.GruposViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')), # Auth routes - login / register
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')), # caminho p/login na API
    path('', include('jogovarejo.urls')), # Essa linha precisa ser a última porque ela contém a "re_path (...., views.pages, ....)" (que trata as URLs inexistentes)       
]

jogovarejo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from django import template
from django.template import loader
from rest_framework import viewsets, permissions

from .models import Controle, Grupo, Movimento, IndicadoresDoGrupo
from .dinamica import ProcessaUmDia, RetrocedeUmDia
from .serializers import IndicadoresSerializer, GruposSerializer


def numeroGrupoDoUsuario (loginUsuario):
    if loginUsuario   == 'grupo1':  numGrupo = 1
    elif loginUsuario == 'grupo2':  numGrupo = 2
    elif loginUsuario == 'grupo3':  numGrupo = 3
    elif loginUsuario == 'grupo4':  numGrupo = 4
    elif loginUsuario == 'grupo5':  numGrupo = 5
    elif loginUsuario == 'grupo6':  numGrupo = 6
    elif loginUsuario == 'grupo7':  numGrupo = 7
    elif loginUsuario == 'grupo8':  numGrupo = 8
    elif loginUsuario == 'grupo9':  numGrupo = 9
    elif loginUsuario == 'grupo10': numGrupo = 10
    elif loginUsuario == 'grupo11': numGrupo = 11
    elif loginUsuario == 'grupo12': numGrupo = 12
    return numGrupo


@login_required(login_url="/login/")
def index (request):
    loginUsuario = request.user.username
    if loginUsuario == 'professor':
        controle = Controle.objects.filter (Nome='Ativo').first()
        grupos = Grupo.objects.filter (Ativo=True).order_by ('Numero')
        contexto = {'tela'   : 'professor', 
                    'fase'   : controle.Fase,
                    'grupos' : grupos}
        return render (request, 'jogovarejo/index.html', contexto)
    else:
        numGrupo = numeroGrupoDoUsuario (loginUsuario)
        fase = Controle.objects.filter (Nome='Ativo').first().Fase
        if fase == 1:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheFormulacao', args=(str(numGrupo))))
        elif fase == 2:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(str(numGrupo))))
        elif fase == 3:
            return HttpResponseRedirect (reverse ('jogovarejo:detalheAvaliacao', args=(str(numGrupo))))


@login_required(login_url="/login/")
def salvaMetodo (request):
    if request.method == 'POST':
        numGrupo = request.POST.get('numGrupo')
        quando   = request.POST.get('quando')
        quanto   = request.POST.get('quanto')
        try:
            grupo = Grupo.objects.get(Numero=numGrupo)
            grupo.Quando  = quando
            grupo.Quanto  = quanto
            grupo.Fase1Ok = True
            grupo.save()
            messages.success (request, 'Gravação bem sucedida! Aguarde a Fase 2 ou altere seu método, se desejar.')
        except ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheFormulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def detalheFormulacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = Grupo.objects.get(Numero=numeroGrupo)
    contexto = {'tela'       : 'alunoFormulacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo}
    return render (request, 'jogovarejo/detalheformula.html', contexto)


@login_required(login_url="/login/")
def avancaUmDia (request):
    if request.method == 'POST':
        numGrupo        = request.POST.get('numGrupo')
        diaNaEstacaoStr = request.POST.get('diaCorrenteNaEstacao')
        quantidadeStr   = request.POST.get('novaCompra')
        try:
            grOperador = Grupo.objects.get (Numero=numGrupo)
            grGerente  = Grupo.objects.filter (GrupoOperador=grOperador).first()
            diaNaEstacao = int (diaNaEstacaoStr)
            if diaNaEstacao == grGerente.DiaCorrente:
                try:
                    quantidade = int (quantidadeStr)
                    if quantidade >= 0:
                        mensagem = ProcessaUmDia (grGerente, quantidade)
                        messages.success (request, mensagem)
                    else:
                        messages.error (request, 'Edição inválida. Tente de novo')
                except ValueError:
                    messages.error (request, 'Edição inválida. Tente de novo')
            else:
                messages.error (request, 'Data inválida.')
        except ValueError or ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def retrocedeUmdia (request):
    if request.method == 'POST':
        numGrupo = request.POST.get('numGrupo')
        try:
            grOperador = Grupo.objects.get (Numero=numGrupo)
            grGerente  = Grupo.objects.filter (GrupoOperador=grOperador).first()
            mensagem = RetrocedeUmDia (grGerente)
            messages.success (request, mensagem)
        except ObjectDoesNotExist:
            messages.error (request, 'Aconteceu algo de errado. Tente de novo por favor')
    return HttpResponseRedirect (reverse ('jogovarejo:detalheSimulacao', args=(numGrupo)))


@login_required(login_url="/login/")
def detalheSimulacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = Grupo.objects.get(Numero=numeroGrupo)  # "grupo" é o grupo operador
    grGerente  = Grupo.objects.filter (GrupoOperador=grupo).first()
    moviDeHoje = Movimento.objects.filter(Grupo=grGerente, Dia=grGerente.DiaCorrente).first()
    historico  = Movimento.objects.filter (Grupo=grGerente).order_by ('Dia')
    contexto = {'tela'       : 'alunoSimulacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo,    # "grupo" é o grupo operador
                'hoje'       : grupo.DiaCorrenteDoGrupoComoOperador, 
                'grGerente'  : grGerente,
                'moviDeHoje' : moviDeHoje,
                'historico'  : historico}
    return render (request, 'jogovarejo/detalhesimula.html', contexto)


@login_required(login_url="/login/")
def detalheAvaliacao (request, numeroGrupo):
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupo      = IndicadoresDoGrupo.objects.get(Numero=numeroGrupo)
    historico  = Movimento.objects.filter (Grupo=grupo).order_by ('Dia')
    contexto = {'tela'       : 'alunoAvaliacao', 
                'fase'       : controle.Fase,
                'grupo'      : grupo,
                'hoje'       : grupo.DiaCorrente, 
                'historico'  : historico}
    return render (request, 'jogovarejo/detalheavalia.html', contexto)


def obtemDecisoesDosGrupos ():
    controle   = Controle.objects.filter (Nome='Ativo').first()
    grupos = Grupo.objects.filter (Ativo=True).order_by ('Numero')
    # Cria primeira linha (que será mostrada como primeira coluna) para mostrar os dias:
    decisoes = []
    decisoesGrupo = ['Dia']
    for dia in range (1, controle.Duracao+1):
        decisoesGrupo.append (dia)
    decisoes.append (decisoesGrupo)
    # Inicializa restante da matriz com nome dos grupos e decisão "-1":
    for grupo in grupos:
        decisoesGrupo = [grupo.Numero]
        for dia in range (1, controle.Duracao+1):
            decisoesGrupo.append (-1)
        decisoes.append (decisoesGrupo)
    # Agora obtem e atribui decisoes:
    for grupo in grupos:
        historico  = Movimento.objects.filter (Grupo=grupo).order_by ('Dia')
        for histDia in historico:
            if histDia.Comprado != None:
                decisoes [grupo.Numero] [histDia.Dia] = histDia.Comprado
    # Por fim transpõe a matriz, pois será construida linha a linha (grupos nas colunas, dias nas linhas)
        decisoes_transpostas = list (map (list, zip(*decisoes)))
        # Para entender o comando acima:
        # - o operador "*" desempacota a "lista de lista" em "listas"
        # - a função "zip" transpõe os elementos das listas recebidas retornando-as como tuplas
        # - a função "list" mais interna transforma uma tupla em uma lista
        # - a função "map" aplica a função "list" a cada uma das tuplas transformando-as, portanto, em listas
        # - a função "list" mais externa, por fim, transforma o conjunto de listas em uma lista de listas
    return decisoes_transpostas


@login_required(login_url="/login/")
def decisoesDosGrupos (request):
    controle = Controle.objects.filter (Nome='Ativo').first()
    contexto = {'tela'     : 'decisoes',
                'fase'     : controle.Fase,
                'decisoes' : obtemDecisoesDosGrupos}
    return render (request, 'jogovarejo/decisoes.html', contexto)


@login_required(login_url="/login/")
def avancaFase (request):
    if request.method == 'POST':
        controle = Controle.objects.filter (Nome='Ativo').first()
        if controle.Fase < 3:
            controle.Fase += 1
            controle.save()
            messages.success (request, 'Fase avançada com sucesso')
        else:
            messages.error (request, 'Não foi possivel avançar de fase')
    return HttpResponseRedirect (reverse ('jogovarejo:index'))


@login_required(login_url="/login/")
def retrocedeFase (request):
    if request.method == 'POST':
        controle = Controle.objects.filter (Nome='Ativo').first()
        if controle.Fase > 1:
            controle.Fase -= 1
            controle.save()
            messages.success (request, 'Fase retrocedida com sucesso')
        else:
            messages.error (request, 'Não foi possivel retroceder fase')
    return HttpResponseRedirect (reverse ('jogovarejo:index'))


@login_required(login_url="/login/")
def sobre (request):
    contexto = {'tela' : 'sobre'}
    return render (request, 'jogovarejo/sobre.html', contexto)

jogovarejo/templates/jogovarejo/decisoes.html
{% extends "layouts/base.html" %}

{% block title %} Jogar Avaliação {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% if decisoes %}

    <div class="col-12 mt-2 mb-8">
        <div class="card border-light shadow-sm">    <!-- HISTÓRICO -->
            <div class="card-header">    <!-- Título -->
                <div class="row align-items-center">
                    <div class="col text-center">
                        <h2 class="h4"><b>Decisões de Compra dos Grupos</b></h2>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">    <!-- Cabeçalho da tabela" -->
                        <tr>
                            {% for elemento in decisoes.0 %}  <!-- Observa que aqui não posso acessar elementos da lista como no Python" -->
                                <th scope="col" style="text-align: right">{{ elemento }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>                        <!-- Corpo da tabela" -->
                        {% for umaLinha in decisoes %}
                            {% if not forloop.first %}
                                <tr>
                                    {% for elemento in umaLinha %}
                                        <td style="text-align: right">{{ elemento }}</td>
                                    {% endfor %}
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% else %}
    <p>Ocorreu algo errado.</p>
{% endif %}


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

jogovarejo/templates/jogovarejo/detalhefase1.html
{% extends "layouts/base.html" %}

{% block title %} Jogar Fase 1 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% if grupo %}

    <div class="col-12 px-0 mb-4">   <!-- Indicação de qual é o GRUPO" -->
        <div class="mb-4">
            <label class="fs-4 fw-extrabold mb-0">{{ grupo.Nome }} - Fase {{ fase }}</label>
        </div>
    </div>

    <div class="row mt-4 mb-2">
        <div class="col-12 px-0 text-center">
            <label class="fs-4 fw-bold mb-0">Instruções ao seu operador:</label>
        </div>
    </div>
    
    <div class="row mb-8">     <!-- Formulario p/ editar QUANDO e QUANTO -->
        <form action="{% url 'jogovarejo:salvaMetodo' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="row">
                    <div class="col-12 col-xl-6 my-4">   <!-- QUANDO E QUANTO COMPRAR -->
                        <label for="quando">Quando comprar</label>
                        <textarea class="form-control" name="quando" id="quando" rows="6" style="font-size: 18px" required>{{ grupo.Quando }}</textarea>
                    </div>
                    <div class="col-12 col-xl-6 my-4">
                        <label for="quanto">Quanto comprar</label>
                        <textarea class="form-control" name="quanto" id="quanto" rows="6" style="font-size: 18px" required>{{ grupo.Quanto }}</textarea>
                    </div>
                    <input type="hidden" name="numGrupo" value="{{ grupo.Numero }}">
                    {% if fase == 1 or request.user.username == "professor" %}
                        <div class="col-12 col-xl-6">
                            <input class="btn btn-dark" type="submit" value="Salvar" style="color: #ffffff; background-color: #262B40">
                        </div>
                    {% endif %}
                </div>
            </fieldset>
        </form>
        <div class="row mt-2">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <!--  <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>-->
                        {% if message.tags == "success" %} <div class ="h5" style="color: green">{{ message }}</div> {% endif %}
                        {% if message.tags == "error" %}   <div class ="h5" style="color: red"  >{{ message }}</div> {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

{% else %}
    <p>Não existe o item.</p>
{% endif %}


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

jogovarejo/templates/jogovarejo/detalheformula.html
{% extends "layouts/base.html" %}

{% block title %} Jogar Formulação {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% if grupo %}

    <div class="col-12 px-0 mb-3">   <!-- Indicação de qual é o GRUPO" -->
        <label class="fs-4 fw-extrabold mb-0">{{ grupo.Nome }}</label>
    </div>
    {% if fase == 1 %}
        <p class="lead">Estamos na <b>Fase 1</b>. Escreva nos campos "quando comprar" e "quanto comprar" abaixo suas "instruções ao operador", que deem 
            forma a sua proposta de sistema de reposição do estoque para o caso proposto. Conclua teclando em "salvar".</p>
    {% endif %}

    <div class="row mt-4 mb-2">
        <div class="col-12 px-0 text-center">
            <label class="fs-4 fw-bold mb-0">Instruções ao seu operador:</label>
        </div>
    </div>
    
    <div class="row mb-8">     <!-- Formulario p/ editar QUANDO e QUANTO -->
        <form action="{% url 'jogovarejo:salvaMetodo' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="row">
                    <div class="col-12 col-xl-6 my-4">   <!-- QUANDO E QUANTO COMPRAR -->
                        <label for="quando">Quando comprar</label>
                        <textarea class="form-control" name="quando" id="quando" rows="6" style="font-size: 18px" required>{{ grupo.Quando }}</textarea>
                    </div>
                    <div class="col-12 col-xl-6 my-4">
                        <label for="quanto">Quanto comprar</label>
                        <textarea class="form-control" name="quanto" id="quanto" rows="6" style="font-size: 18px" required>{{ grupo.Quanto }}</textarea>
                    </div>
                    <input type="hidden" name="numGrupo" value="{{ grupo.Numero }}">
                    {% if fase == 1 or request.user.username == "professor" %}
                        <div class="col-12 col-xl-6">
                            <input class="btn btn-dark" type="submit" value="Salvar" style="color: #ffffff; background-color: #262B40">
                        </div>
                    {% endif %}
                </div>
            </fieldset>
        </form>
        <div class="row mt-2">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <!--  <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>-->
                        {% if message.tags == "success" %} <div class ="h5" style="color: green">{{ message }}</div> {% endif %}
                        {% if message.tags == "error" %}   <div class ="h5" style="color: red"  >{{ message }}</div> {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

{% else %}
    <p>Não existe o item.</p>
{% endif %}


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

jogovarejo/templates/jogovarejo/index.html
{% extends "layouts/base.html" %}

{% block title %} Jogar {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% if grupos %}

    {% if messages %}    <!-- Exibição de mensagem ao usuário posterior à edição  -->
    <div class="messages">
        {% for message in messages %}
            {% if message.tags == "success" %} <div class ="h6" style="color: green">{{ message }}</div> {% endif %}
            {% if message.tags == "error" %}   <div class ="h6" style="color: red"  >{{ message }}</div> {% endif %}
            <!--  <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>-->
        {% endfor %}
    </div>
    {% endif %}

    <div class="col-12 px-0 mb-4">   <!-- Indicação de qual é a FASE" -->
        <div class="mb-4">
            <label class="fs-4 fw-extrabold mb-0">Fase {{ fase }}</label>
        </div>
    </div>

    <div class="row mt-2 mb-10">
        {% for grupo in grupos %}
            <div class="col-12 col-xl-3">    <!-- SITUACAO DE UM GRUPO" -->
                <div class="col-12 px-0">
                    <label class="fs-5 fw-extrabold mb-0">   <!-- Titulo "NOME ITEM" -->
                        {% if fase == 1 %}
                            <a href="{% url 'jogovarejo:detalheFormulacao' grupo.Numero %}">{{ grupo.Nome }}</a>
                        {% endif %}
                        {% if fase == 2 %}
                            <a href="{% url 'jogovarejo:detalheSimulacao' grupo.Numero %}">{{ grupo.Nome }}</a>
                        {% endif %}
                        {% if fase == 3 %}
                            <a href="{% url 'jogovarejo:detalheAvaliacao' grupo.Numero %}">{{ grupo.Nome }}</a>
                        {% endif %}
                    </label>
                </div>
                <div class="col-12 px-0 mb-1">
                    <div class="card border-0 shadow">   <!-- Card "MOVIMENTAÇÃO" -->
                        <div class="card-body">
                            <div class="d-flex align-items-center justify-content-between border-bottom pb-1">   <!-- "Situação Fase 1" -->
                                {% if grupo.Fase1Ok == True %}
                                    <div class="h6 mb-0 d-flex align-items-center" style="color: green">
                                        Fase 1
                                    </div>
                                    <div class="d-flex align-items-center fw-bold" style="color: green">
                                        Ok
                                    </div>
                                {% else %}
                                    <div class="h6 mb-0 d-flex align-items-center" style="color: red">
                                        Fase 1
                                    </div>
                                    <div class="d-flex align-items-center fw-bold" style="color: red">
                                        Pendente
                                    </div>
                                {% endif %}
                            </div>
                            <div class="d-flex align-items-center justify-content-between border-bottom pb-1">  <!-- "Grupo operador" -->
                                <div class="h6 mb-0 d-flex align-items-center">
                                    Grupo operador
                                </div>
                                <div class="d-flex align-items-center fw-bold">
                                    {{ grupo.GrupoOperador }}
                                </div>
                            </div>
                            <div class="d-flex align-items-center justify-content-between pt-1">   <!-- "Simulolu até..." -->
                                {% if grupo.Fase2DoGrupoComoOperadorOk == True %}
                                    <div class="h6 mb-0 d-flex align-items-center" style="color: green">
                                        Fase 2
                                    </div>
                                    <div class="d-flex align-items-center fw-bold" style="color: green">
                                        Ok
                                    </div>
                                {% else %}
                                    <div class="h6 mb-0 d-flex align-items-center">
                                        Simulou até
                                    </div>
                                    <div class="d-flex align-items-center fw-bold">
                                        {{ grupo.DiaCorrenteDoGrupoComoOperador }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% else %}
    <p>Não existem grupos.</p>
{% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

jogovarejo/templates/jogovarejo/sobre.html
{% extends "layouts/base.html" %}

{% block title %} Sobre {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="mt-6 mb-6">
    <blockquote class="blockquote text-left">
        Jogo Varejo - 2024
    </blockquote>
    
    <blockquote class="blockquote text-left">
        Aplicativo para jogo de gestão de um estágio da cadeia de suprimentos, no caso o varejo.
    </blockquote>
</div>

<div class="mb-6">
    <blockquote class="blockquote text-left">
        Projetado pelo Professor Euclydes da Cunha Neto (euclydescn@outlook.com) para ser usado em suas atividades didáticas.
    </blockquote>

    <blockquote class="blockquote text-left">
        Direitos reservados.
    </blockquote>
</div>

<div class="mb-8">
    <blockquote class="blockquote text-left">
        Mentoria em desenvolvimento de software: Edward José Pacheco Condori (edwardspc@gmail.com).
    </blockquote>
    
</div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}